config/routes.rb
Rails.application.routes.draw do

  get 'watched_movies/new', to: 'watched_movies#new', as: 'new_watched_movie'
  post 'watched_movies/create', to: 'watched_movies#create'

  root to: 'dashboard#index'

  get '/profile', to: 'dashboard#profile', as: "profile"

  resources :users
  resources :movies
  resources :genres

  get    '/login',  to: 'session#new'
  post   '/login',  to: 'session#create'
  delete '/logout', to: 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, uniqueness: true

  def self.to_array_for_select_field
    Genre.all.map{ |genre| [genre.name, genre.id] }
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.connection.select_all("SELECT * FROM genres;")
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(genre) do |f| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <p id="notice"><%= notice %></p>

      <h1>Genres</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td>
                <%= genre["name"] %>
              </td>
              <td><%= link_to 'Show', genre_url(genre["id"]),
                class: "btn btn-info btn-sm"%>
              </td>
              <td><%= link_to 'Edit', edit_genre_path(genre["id"]),
                class: "btn btn-warning btn-sm" %>
              </td>
              <td>
                <%= link_to 'Destroy', genre_url(genre["id"]),
                 method: :delete,
                 data: { confirm: 'Are you sure?' },
                 class: "btn btn-danger btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Genre', new_genre_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>