config/routes.rb
Rails.application.routes.draw do

  get 'watched_movies/new', to: 'watched_movies#new', as: 'new_watched_movie'
  post 'watched_movies/create', to: 'watched_movies#create'

  root to: 'dashboard#index'

  get '/profile', to: 'dashboard#profile', as: "profile"

  resources :users
  resources :movies
  resources :genres

  get    '/login',  to: 'session#new'
  post   '/login',  to: 'session#create'
  delete '/logout', to: 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :set_genres, only: [:new, :edit, :update]
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.connection
      .select_all("SELECT m.id AS id,
                          m.title AS title,
                          m.released AS released, 
                          g.name AS genre_name
                    FROM movies m
                    INNER JOIN genres g
                    ON g.id = m.genre_id;")
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def set_genres
      @genres = Genre.to_array_for_select_field
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :released, :genre_id)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :released %>
    <%= f.date_select :released %>
  </div>

  <div class="form-group">
    <%= f.label :genre_id %>
    <%= f.select :genre_id, @genres, {}, class: "form-control"%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="continer-fluid">
  <div class="row">
    <div class="col-md-12">
      <p id="notice"><%= notice %></p>

      <h1>Movies</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Released</th>
            <th>Genre</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @movies.each do |movie| %>
            <tr>
              <td><%= movie["title"] %></td>
              <td><%= movie["released"].strftime("%Y-%m-%d") %></td>
              <!-- using #{} which is essentially toString() -->
              <td><%= movie["genre_name"] %></td>
              <td>
                <%= link_to 'Show', movie_url(movie["id"]), class: "btn btn-info btn-sm"%>
              </td>
              <td>
                <%= link_to 'Edit', edit_movie_path(movie["id"]), class: "btn btn-warning btn-sm" %>
              </td>
              <td>
                <%= link_to 'Destroy', movie_url(movie["id"]),
                    method: :delete,
                    data: { confirm: 'Are you sure?' },
                    class: "btn btn-danger btn-sm"%></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Movie', new_movie_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Released:</strong>
  <%= @movie.released %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre.name %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>